version: '2'
services:
  web:
    build: .
    image: too-mean
    ports:
      - "3080:3080"
      - "3443:3443"
    links:
      - mongo
    volumes:
      - ./modules:/usr/src/app/modules/
    environment:
      - TOOMEAN_MONGO_HOST=mongo
    env_file:
      - .env
  mongo:
    image: "mongo"
